codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default: off
      server:
        flags:
          - server
        if_ci_failed: error
        if_not_found: failure
        target: 85%
        threshold: 0%
      python-client:
        flags:
          - python-client
        if_ci_failed: error
        if_not_found: failure
        target: 80%
        threshold: 0%
    patch:
      default: off
      server:
        flags:
          - server
        if_ci_failed: error
        if_not_found: failure
        target: 90%
        threshold: 0%
      python-client:
        flags:
          - python-client
        if_ci_failed: error
        if_not_found: failure
        target: 90%
        threshold: 0%

comment:
  behavior: default
  layout: "header, diff, flags, files"
  require_base: true
  require_changes: false
  require_head: true

flags:
  server:
    carryforward: false
    paths:
      - apps/server/
  python-client:
    carryforward: false
    paths:
      - clients/python/
