[project]
name = "niyan"
version = "0.4.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.43.97",
    "django~=5.2.17",
    "django-environ>=0.14.0",
    "django-ninja>=1.7.0",
    "gunicorn>=23.0.0,<24",
    "psycopg[binary]>=3.3.5",
    "whitenoise>=6.11.0",
]

[dependency-groups]
dev = [
    "coverage>=7.10",
    "fsspec>=2025.3.0",
]

[tool.coverage.run]
branch = true
omit = ["manage.py", "*/asgi.py", "*/migrations/*", "*/tests/*", "*/wsgi.py"]
relative_files = true
source = ["."]

[tool.coverage.report]
omit = ["manage.py", "*/asgi.py", "*/migrations/*", "*/tests/*", "*/wsgi.py"]
precision = 1
show_missing = true

[tool.coverage.html]
directory = "htmlcov"

[tool.coverage.xml]
output = "coverage.xml"
