# Generated by Django 5.2.17 on 2026-09-17 02:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Used for login and the initial personal namespace path.', max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Use letters, numbers, periods, underscores, or hyphens; begin and end with a letter or number.', regex='^[A-Za-z0-9](?:[A-Za-z0-9._-]*[A-Za-z0-9])?$')]),
        ),
    ]
