"""
Django settings for the project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import environ
from django.core.exceptions import ImproperlyConfigured

from datasets.object_storage import S3Configuration

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = env('NIYAN_SECRET_KEY')

DEBUG = env.bool('NIYAN_DEBUG', default=False)

ALLOWED_HOSTS = env.list('NIYAN_ALLOWED_HOSTS', default=[])


# Application definition

INSTALLED_APPS = [
    'accounts.apps.AccountsConfig',
    'namespaces.apps.NamespacesConfig',
    'datasets.apps.DatasetsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': env.db('NIYAN_DATABASE_URL'),
}
test_database_name = env('NIYAN_TEST_DATABASE_NAME', default=None)
if test_database_name:
    DATABASES['default'].setdefault('TEST', {})['NAME'] = test_database_name

REPOSITORIES_ROOT = Path(env('NIYAN_GIT_ROOT')).expanduser()

try:
    NIYAN_S3_CONFIGURATION = S3Configuration(
        endpoint_url=env('NIYAN_S3_ENDPOINT_URL', default=None),
        region_name=env('NIYAN_S3_REGION', default='us-east-1'),
        bucket=env('NIYAN_S3_BUCKET'),
        access_key_id=env('NIYAN_S3_ACCESS_KEY_ID', default=None),
        secret_access_key=env('NIYAN_S3_SECRET_ACCESS_KEY', default=None),
        session_token=env('NIYAN_S3_SESSION_TOKEN', default=None),
        addressing_style=env('NIYAN_S3_ADDRESSING_STYLE', default='auto'),
        signature_version=env('NIYAN_S3_SIGNATURE_VERSION', default='s3v4'),
        key_prefix=env('NIYAN_S3_KEY_PREFIX', default='niyan'),
        sha256_checksums=env.bool('NIYAN_S3_SHA256_CHECKSUMS', default=False),
        verify_tls=env.bool('NIYAN_S3_VERIFY_TLS', default=True),
        connect_timeout_seconds=env.int('NIYAN_S3_CONNECT_TIMEOUT_SECONDS', default=5),
        read_timeout_seconds=env.int('NIYAN_S3_READ_TIMEOUT_SECONDS', default=30),
        max_attempts=env.int('NIYAN_S3_MAX_ATTEMPTS', default=3),
    )
except ValueError as error:
    raise ImproperlyConfigured(str(error)) from error

NIYAN_ACCESS_TOKEN_MAX_DAYS = env.int('NIYAN_ACCESS_TOKEN_MAX_DAYS', default=365)
NIYAN_DEVICE_AUTHORIZATION_LIFETIME_SECONDS = env.int('NIYAN_DEVICE_AUTHORIZATION_LIFETIME_SECONDS', default=600)
NIYAN_DEVICE_AUTHORIZATION_POLL_INTERVAL_SECONDS = env.int('NIYAN_DEVICE_AUTHORIZATION_POLL_INTERVAL_SECONDS', default=5)
NIYAN_LFS_TRANSFER_ACTION_LIFETIME_SECONDS = env.int('NIYAN_LFS_TRANSFER_ACTION_LIFETIME_SECONDS', default=900)
NIYAN_LFS_MULTIPART_THRESHOLD_BYTES = env.int('NIYAN_LFS_MULTIPART_THRESHOLD_BYTES', default=100 * 1024 * 1024)
NIYAN_LFS_MULTIPART_PART_SIZE_BYTES = env.int('NIYAN_LFS_MULTIPART_PART_SIZE_BYTES', default=64 * 1024 * 1024)
NIYAN_LFS_MULTIPART_SESSION_LIFETIME_SECONDS = env.int('NIYAN_LFS_MULTIPART_SESSION_LIFETIME_SECONDS', default=24 * 60 * 60)
NIYAN_LFS_ORPHAN_GRACE_PERIOD_SECONDS = env.int('NIYAN_LFS_ORPHAN_GRACE_PERIOD_SECONDS', default=7 * 24 * 60 * 60)
NIYAN_LFS_MAINTENANCE_INTERVAL_SECONDS = env.int('NIYAN_LFS_MAINTENANCE_INTERVAL_SECONDS', default=300)
NIYAN_GIT_PUSH_CONTEXT_LIFETIME_SECONDS = env.int('NIYAN_GIT_PUSH_CONTEXT_LIFETIME_SECONDS', default=5 * 60)
NIYAN_GIT_PUSH_LEASE_LIFETIME_SECONDS = env.int('NIYAN_GIT_PUSH_LEASE_LIFETIME_SECONDS', default=15 * 60)
NIYAN_BROWSER_DRAFT_LIFETIME_SECONDS = env.int('NIYAN_BROWSER_DRAFT_LIFETIME_SECONDS', default=24 * 60 * 60)
NIYAN_REDIS_URL = env('NIYAN_REDIS_URL', default=None)

if not 1 <= NIYAN_ACCESS_TOKEN_MAX_DAYS <= 365:
    raise ImproperlyConfigured('NIYAN_ACCESS_TOKEN_MAX_DAYS must be between 1 and 365.')
if NIYAN_DEVICE_AUTHORIZATION_LIFETIME_SECONDS < 1:
    raise ImproperlyConfigured('NIYAN_DEVICE_AUTHORIZATION_LIFETIME_SECONDS must be positive.')
if not 1 <= NIYAN_DEVICE_AUTHORIZATION_POLL_INTERVAL_SECONDS <= NIYAN_DEVICE_AUTHORIZATION_LIFETIME_SECONDS:
    raise ImproperlyConfigured('NIYAN_DEVICE_AUTHORIZATION_POLL_INTERVAL_SECONDS must be positive and no greater than the device authorization lifetime.')
if not 1 <= NIYAN_LFS_TRANSFER_ACTION_LIFETIME_SECONDS <= 3600:
    raise ImproperlyConfigured('NIYAN_LFS_TRANSFER_ACTION_LIFETIME_SECONDS must be between 1 and 3600.')
if not 1 <= NIYAN_LFS_MULTIPART_THRESHOLD_BYTES <= 5 * 1024 * 1024 * 1024 * 1024:
    raise ImproperlyConfigured('NIYAN_LFS_MULTIPART_THRESHOLD_BYTES must be between 1 byte and 5 TiB.')
if not 5 * 1024 * 1024 <= NIYAN_LFS_MULTIPART_PART_SIZE_BYTES <= 5 * 1024 * 1024 * 1024:
    raise ImproperlyConfigured('NIYAN_LFS_MULTIPART_PART_SIZE_BYTES must be between 5 MiB and 5 GiB.')
if not 1 <= NIYAN_LFS_MULTIPART_SESSION_LIFETIME_SECONDS <= 7 * 24 * 60 * 60:
    raise ImproperlyConfigured('NIYAN_LFS_MULTIPART_SESSION_LIFETIME_SECONDS must be between 1 second and 7 days.')
if NIYAN_LFS_ORPHAN_GRACE_PERIOD_SECONDS < 1:
    raise ImproperlyConfigured('NIYAN_LFS_ORPHAN_GRACE_PERIOD_SECONDS must be positive.')
if NIYAN_LFS_MAINTENANCE_INTERVAL_SECONDS < 1:
    raise ImproperlyConfigured('NIYAN_LFS_MAINTENANCE_INTERVAL_SECONDS must be positive.')
if not 1 <= NIYAN_GIT_PUSH_CONTEXT_LIFETIME_SECONDS <= 60 * 60:
    raise ImproperlyConfigured('NIYAN_GIT_PUSH_CONTEXT_LIFETIME_SECONDS must be between 1 second and 1 hour.')
if not NIYAN_GIT_PUSH_CONTEXT_LIFETIME_SECONDS <= NIYAN_GIT_PUSH_LEASE_LIFETIME_SECONDS <= 24 * 60 * 60:
    raise ImproperlyConfigured('NIYAN_GIT_PUSH_LEASE_LIFETIME_SECONDS must be at least the push-context lifetime and no greater than 1 day.')


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
NIYAN_WEB_DIST_ROOT = Path(env('NIYAN_WEB_DIST_ROOT', default=BASE_DIR.parent / 'web' / '.output' / 'public')).expanduser()
STATICFILES_DIRS = [NIYAN_WEB_DIST_ROOT / 'static'] if (NIYAN_WEB_DIST_ROOT / 'static').is_dir() else []
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage'},
}
WHITENOISE_MAX_AGE = 31_536_000

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
