import io
import unittest
from urllib.error import HTTPError

import fsspec
import polars

from niyan.errors import ApiError
from niyan.filesystem import NiyanFileSystem


GIT_CONTENT = b'sample,value\nalpha,1\nbeta,2\n'
LFS_SIZE = 5_000_000_000
COMMIT = 'a' * 40
LFS_OID = 'e' * 64


class ReadApi:
    """Return exact read actions while recording refresh behavior."""

    instances = []

    def __init__(self, host, *, token=None, timeout=30):
        self.host = host
        self.token = token
        self.timeout = timeout
        self.authorizations = []
        type(self).instances.append(self)

    def capabilities(self):
        return 200, {'api_versions': ['v1'], 'filesystem': {'protocol_version': 1, 'features': ['dataset-path-resolution', 'exact-revision-resolution', 'repository-metadata', 'git-blob-reads', 'authorized-lfs-download-actions']}}

    def resolve_dataset(self, locator_path):
        if not locator_path.startswith('lab/images'):
            raise ApiError('Missing', status=404, code='dataset_not_found')
        return 200, {'id': 'dataset-id', 'path': 'lab/images', 'repository_path': locator_path.removeprefix('lab/images').strip('/')}

    def resolve_revision(self, dataset_id, *, revision=None):
        return 200, {'dataset_id': dataset_id, 'requested_revision': revision or 'main', 'resolved_commit': COMMIT}

    def authorize_repository_download(self, dataset_id, *, revision, path):
        self.authorizations.append((dataset_id, revision, path))
        if path == 'nested/sample.csv':
            return 200, {
                'resolved_commit': revision,
                'path': path,
                'size': len(GIT_CONTENT),
                'object_id': 'c' * 40,
                'lfs_object_id': None,
                'storage': 'git',
                'method': 'GET',
                'url': 'https://data.example.test/api/v1/raw',
                'headers': {},
                'expires_in': None,
                'range_supported': True,
            }
        generation = sum(1 for _, _, authorized_path in self.authorizations if authorized_path == path)
        return 200, {
            'resolved_commit': revision,
            'path': path,
            'size': LFS_SIZE,
            'object_id': 'd' * 40,
            'lfs_object_id': LFS_OID,
            'storage': 'lfs',
            'method': 'GET',
            'url': f'https://objects.example.test/signed-{"expired" if generation == 1 else "fresh"}?secret=hidden',
            'headers': {'X-Signed-Header': 'required'},
            'expires_in': 300,
            'range_supported': True,
        }


class TransferResponse:
    """Provide the bounded urllib response surface used by the client."""

    def __init__(self, content, *, content_range):
        self.status = 206
        self.headers = {'Content-Range': content_range}
        self.content = content

    def read(self, amount):
        return self.content[:amount]

    def getcode(self):
        return self.status

    def __enter__(self):
        return self

    def __exit__(self, exception_type, exception, traceback):
        return False


class TransferOpener:
    """Serve generated byte ranges without allocating the simulated LFS object."""

    def __init__(self):
        self.requests = []

    def open(self, request, timeout):
        range_header = request.get_header('Range')
        authorization = request.get_header('Authorization')
        self.requests.append((request.full_url, range_header, authorization, request.get_header('X-signed-header')))
        if 'signed-expired' in request.full_url:
            raise HTTPError(request.full_url, 403, 'Expired', {}, io.BytesIO())
        start, end = _parse_range(range_header)
        if '/api/v1/raw' in request.full_url:
            content = GIT_CONTENT[start : end + 1]
            size = len(GIT_CONTENT)
        else:
            content = bytes(index % 256 for index in range(start, end + 1))
            size = LFS_SIZE
        return TransferResponse(content, content_range=f'bytes {start}-{end}/{size}')


def _parse_range(header):
    """Parse the exact bounded range emitted by the filesystem."""

    start, end = header.removeprefix('bytes=').split('-', 1)
    return int(start), int(end)


class FileSystemReadTests(unittest.TestCase):
    """Verify pinned buffered reads for Git and Git LFS content."""

    def setUp(self):
        """Create one filesystem with deterministic API and transfer doubles."""

        ReadApi.instances = []
        self.opener = TransferOpener()
        self.fs = NiyanFileSystem(token='niyan_test-token', api_factory=ReadApi, transfer_opener=self.opener, block_size=4)

    def test_git_blob_supports_read_seek_tell_and_bearer_authentication(self):
        """Read ordinary blobs through the ranged repository endpoint."""

        with self.fs.open('niyan://data.example.test/lab/images/nested/sample.csv?revision=main', 'rb') as file:
            self.assertEqual(file.read(3), GIT_CONTENT[:3])
            self.assertEqual(file.tell(), 3)
            file.seek(10)
            self.assertEqual(file.read(4), GIT_CONTENT[10:14])

        self.assertTrue(all(request[2] == 'Bearer niyan_test-token' for request in self.opener.requests))
        self.assertEqual(ReadApi.instances[-1].authorizations, [('dataset-id', COMMIT, 'nested/sample.csv')])

    def test_lfs_reads_refresh_an_expired_action_without_losing_position(self):
        """Read noncontiguous multi-gigabyte ranges and safely refresh authorization."""

        with self.fs.open('niyan://data.example.test/lab/images/large.bin?revision=main', 'rb') as file:
            beginning = file.read(3)
            file.seek(4_000_000_000)
            content = file.read(5)

        self.assertEqual(beginning, bytes(range(3)))
        self.assertEqual(content, bytes(index % 256 for index in range(4_000_000_000, 4_000_000_005)))
        self.assertEqual(len(ReadApi.instances[-1].authorizations), 2)
        self.assertTrue(any(request[1].startswith('bytes=0-') for request in self.opener.requests))
        self.assertTrue(any(request[1].startswith('bytes=4000000000-') for request in self.opener.requests))
        self.assertTrue(all(request[2] is None for request in self.opener.requests))
        self.assertTrue(all(request[3] == 'required' for request in self.opener.requests))

    def test_cat_file_reads_only_the_requested_interval(self):
        """Expose standard fsspec byte-range reads without opening a checkout."""

        content = self.fs.cat_file('niyan://data.example.test/lab/images/nested/sample.csv?revision=main', start=5, end=9)

        self.assertEqual(content, GIT_CONTENT[5:9])
        self.assertEqual(self.opener.requests[-1][1], 'bytes=5-8')

    def test_write_modes_are_rejected_before_transfer(self):
        """Keep the v1 filesystem explicitly read-only."""

        with self.assertRaises(PermissionError):
            self.fs.open('niyan://data.example.test/lab/images/nested/sample.csv', 'wb')

    def test_fsspec_open_uses_the_registered_protocol_without_an_adapter(self):
        """Read through fsspec's normal URL entry point."""

        opened = fsspec.open('niyan://data.example.test/lab/images/nested/sample.csv?revision=main', mode='rb', token='niyan_test-token', api_factory=ReadApi, transfer_opener=self.opener, block_size=4)
        with opened as file:
            self.assertEqual(file.read(4), GIT_CONTENT[:4])

    def test_polars_reads_a_niyan_url_through_standard_fsspec_integration(self):
        """Give a representative downstream consumer no Niyān-specific adapter."""

        frame = polars.read_csv(
            'niyan://data.example.test/lab/images/nested/sample.csv?revision=main',
            storage_options={'token': 'niyan_test-token', 'api_factory': ReadApi, 'transfer_opener': self.opener, 'block_size': 4},
        )

        self.assertEqual(frame.to_dict(as_series=False), {'sample': ['alpha', 'beta'], 'value': [1, 2]})


if __name__ == '__main__':
    unittest.main()
