# Generated by Django 5.2.17 on 2026-09-17 02:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Namespace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('personal', 'Personal'), ('group', 'Group')], max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Use letters, numbers, periods, underscores, or hyphens; begin and end with a letter or number.', regex='^[A-Za-z0-9](?:[A-Za-z0-9._-]*[A-Za-z0-9])?$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personal_namespace', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='namespaces.namespace')),
            ],
        ),
        migrations.CreateModel(
            name='NamespaceMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('maintainer', 'Maintainer'), ('contributor', 'Contributor'), ('reader', 'Reader')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='namespaces.namespace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='namespace_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='namespace',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'personal'), ('owner_user__isnull', False), ('parent__isnull', True)), models.Q(('kind', 'group'), ('owner_user__isnull', True)), _connector='OR'), name='namespace_kind_shape'),
        ),
        migrations.AddConstraint(
            model_name='namespace',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('slug',), name='unique_root_namespace_slug'),
        ),
        migrations.AddConstraint(
            model_name='namespace',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('parent', 'slug'), name='unique_child_namespace_slug'),
        ),
        migrations.AddConstraint(
            model_name='namespacemembership',
            constraint=models.UniqueConstraint(fields=('namespace', 'user'), name='unique_namespace_membership'),
        ),
    ]
